from enum import StrEnum

# projects app
MAX_LENGTH_PROJECT_NAME = 200
MAX_LENGTH_PROJECT_STATUS = 6
PROJECTS_PER_PAGE = 12
SKILL_TRUNCATION_TAIL = 10

# users app
MAX_LENGTH_SKILL_NAME = 124
MAX_LENGTH_USER_NAME = 124
MAX_LENGTH_USER_SURNAME = 124
MAX_LENGTH_USER_PHONE = 12
MAX_LENGTH_USER_ABOUT = 124
USERS_PER_PAGE = 12
IMAGE_SIZE = (256, 256)
IMAGE_FONT_SIZE = round(IMAGE_SIZE[0] * 0.46875)


# colours
class Colors(StrEnum):
    PALE_BLUE = "#DDE7F2"
    SOFT_YELLOW = "#E5E7D6"
    IVORY_LINEN = "#F1E2D2"
    PASTEL = "#DEE8DD"
    LILAC_FROST = "#E8DEEA"
    CLASSIC_ANTHRACITE = "#2F3437"
